# *****************************************************
#     > Do Androids Dream of Electric Sheep? 
#     > File Name   :  Makefile
#     > Author      :  spike
#     > Email       :  Gehirn@yeah.net
#     > Create time :  CST 22:55:21 2020/07/23 四
#     > Comment     :
# *****************************************************

make :
	bash G

open :
	vim ./server.c
